### ISSUE TITLE
Wrong version of vault/sdk?

### ISSUE THREAD

**Issue by chwang-wish** [hashicorp/go-kms-wrapping#13]
In go.mod, it requires sdk/v0.1.14, but newest sdk release is only 0.1.13 at https://github.com/hashicorp/vault/releases. 
And I get
```
go: github.com/hashicorp/vault@v1.4.0 requires
        github.com/hashicorp/go-kms-wrapping@v0.5.1 requires
        github.com/hashicorp/vault/sdk@v0.1.14-0.20191229212425-c478d00be0d6: invalid version: unknown revision c478d00be0d6
```

Is there something wrong or am I missing something?

**Comment by jefferai** [comment]
This is due to relying on an unmerged branch. It's been updated, when the branch is merged I will update again.

**Comment by samtholiya** [comment]
@jefferai any work around?

**Comment by jefferai** [comment]
Yes, master should work fine.

**Comment by chwang-wish** [comment]
Just to provide more information here, I shouldn't have put `github.com/hashicorp/vault v1.4.0` in my go.mod file, instead now I'm using `github.com/hashicorp/vault/api v1.0.4`
